version: "3.9"

services:
  wiremock:
    image: wiremock/wiremock:3.13.1
    container_name: wiremock
    ports:
      - "8080:8080"
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
      - ./wiremock/__files:/home/wiremock/__files
    restart: unless-stopped

  dashboard:
    build: ./dashboard
    container_name: mock-dashboard
    ports:
      - "8081:8081"
    environment:
      - WIREMOCK_URL=http://wiremock:8080
    depends_on:
      - wiremock
